---
  - name: Create {{ webapp_user }} group
    group: name="{{ webapp_user }}" 

  - name: Create {{ webapp_user }} user
    user: 
      name: "{{ webapp_user }}" 
      shell: /bin/bash
      group: "{{ webapp_user }}"
      home: "{{ webapp_root }}"
      create_home: yes
